# Generated by Django 3.2.6 on 2021-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
        migrations.AddField(
            model_name='book',
            name='password',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(default='', max_length=18),
        ),
    ]
